---
title: "cleaning"
author: "JJayes"
date: "25/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
library(glue)
```

## Purpose

Cleaning the data scraped so that each wine is it's own row.

### Reading in data

```{r}
df <- read_rds("data/reviews/reviews_2021-03-13 02-05-pm.rds")
```

### Cleaning

Unnest data

```{r}
df <- df %>% 
  unnest(c(text, title, review_date))
```

Remove lines with no text

```{r}
df <- df %>% 
  filter(nchar(value) > 0)


df <- df %>% 
  group_by(review_url) %>% 
  mutate(review = paste0(value, collapse = " ")) %>% 
  ungroup()

df <- df %>% 
  select(-c(link, page, value))

df <- df %>% 
  distinct()
```

How many wines in this review?

```{r}
df <- df %>% 
  mutate(n_wines = str_count(review, 
                                     "(?=\\s[7-9][0-9](?!\\%|D|d))(\\s[7-9][0-9])"))
```

What are the scores of these wines?

```{r}
df <- df %>% 
  mutate(wine_scores = str_extract_all(review, 
                                     "(?=\\s[7-9][0-9](?!\\%|D|d))(\\s[7-9][0-9])"))
```

What are the words for each review?

```{r}
df <- df %>% 
  unnest(wine_scores) %>% 
  mutate(wine_review_locations = str_locate_all(review, glue("{wine_scores}"))) %>% 
  unnest(wine_review_locations) %>%
  mutate(wine_review_locations = wine_review_locations[,1],
         wine_review_locations = as.numeric(wine_review_locations)) %>% 
  distinct(review_url, wine_scores, wine_review_locations, .keep_all = T) %>%
  group_by(review_url) %>% 
  arrange(wine_review_locations) %>% 
  ungroup() %>% 
  arrange(review_number)

```

How can we get the text from before each score only?

```{r}
df <- df %>% 
  group_by(review_url) %>% 
  mutate(wine_index = row_number()) %>% 
  mutate(review_start = case_when(
    
    wine_index == 1 ~ 0,
    TRUE ~ lag(wine_review_locations)
    
  )) %>% 
  ungroup() %>% 
  arrange(review_number) %>% 
  mutate(text = substr(review, review_start, wine_review_locations))
```

A bit of tidying up

```{r}
df <- df %>% 
  mutate(text = str_remove(text, "^[:space:][7-9][0-9]/100"),
         text = str_remove(text, "^[:space:][7-9][0-9]"))
```

Scores as numbers - remove other cols

```{r}
df <- df %>% 
  select(-c(wine_review_locations, wine_index, review_start, review)) %>% 
  mutate(wine_scores = parse_number(wine_scores))
```

Get price

```{r}
df <- df %>% 
  # get price from review
  mutate(price = str_extract(text, "R[1-9][0-9]+"),
         price_R = parse_number(price))

df %>% 
  ggplot(aes(wine_scores, price_R, colour = review_date)) +
  geom_smooth(method = "lm") +
  geom_jitter(alpha = .5) +
  scale_y_log10()

df %>% 
  ggplot(aes(review_date, wine_scores)) +
  geom_smooth(method = "lm") +
  geom_point()

df %>% view()

df %>% 
  filter(!is.na(price))

```



```{r}
df %>% 
  count(wine_scores, sort = T)

```

